#!/bin/sh /etc/rc.common

SCRIPT_NAME="LED Web UI"
SCRIPT_PGM="http_command.py"
SCRIPT_PATH="/root/http_command.py /root/http_command.html /root/dev/linkit/python"
#LOG_FILE="/root/dev/linkit/python/http_command.log"
LOG_FILE="/dev/null"

START=99
STOP=50
 
start() {       
        echo "Starting $SCRIPT_NAME"
        $SCRIPT_PATH >> $LOG_FILE 2>&1 &
}                
 
stop() {         
        echo "Stopping $SCRIPT_NAME"
        killall -9 `basename $SCRIPT_PGM`
}

