#!/bin/sh

git -C /Media/SD-P1/dev/linkit pull
rsync -ut /Media/SD-P1/dev/linkit/python/http_command.* /root
rsync -ut /Media/SD-P1/dev/linkit/python/images/* /root/images/
rsync -ut /Media/SD-P1/dev/linkit/python/color_command.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/udp_command.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/terminal_colors.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/weather.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/weather_conditions.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/led_command.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/app_ui.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/utils.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/wx.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/sunrise.py /root
rsync -ut /Media/SD-P1/dev/linkit/python/update /root
/etc/init.d/http_command restart
/etc/init.d/udp_command restart
/etc/init.d/weather restart
/etc/init.d/sunrise restart
/etc/init.d/sunset start

