#!/bin/sh /etc/rc.common
 
SCRIPT_NAME="LED Remote Control"
SCRIPT_PGM="remote.py"
SCRIPT_PATH="/root/remote.py"
#LOG_FILE="/root/dev/linkit/python/http_command.log"
LOG_FILE="/dev/null"

START=99
STOP=50
 
start() {       
        echo "Starting $SCRIPT_NAME"
        $SCRIPT_PATH >> $LOG_FILE 2>&1 &
}                
 
stop() {         
        echo "Stopping $SCRIPT_NAME"
        killall -9 `basename $SCRIPT_PGM`
}

