
%include symbols

$render-time 100
$width0 15
$width1 90
$width2 75
$time1 50
$time2 200
$color 1
$seq-type sqs
$fade-type ffd
$step 2

[fancy 10]
  app
  (init)

[init]
  <DRAW-PLUS>:drw
  <render-time>,<render>:sch
  (start)

[start]
  (((worm-start 3)))

#(((worm 1 <time1> <time2> <color> <step>)))

((worm 0 50 200 0 1))
((worm 1 45 195 3 2))
((worm 2 40 190 4 3))

[[worm-start X
  (worm-start-X)
]]

[[worm X TIME1 TIME2 COLOR STEP
  [worm-start-X]
    {seq0-X},<width0>:<seq-type>
    {seq1-X},<width1>:<seq-type>
    {seq2-X},<width2>:<seq-type>
    (worm-draw-X TIME1)
    (worm-advance-X TIME2)

  [worm-draw-X]
    <seq1-X>,<MACRO-SEQ>,<worm-math-X>:snw
    pos
    COLOR:pal
    <fade-type>
    flo
    rst

  [worm-math-X]
    <seq0-X>:seq
    psh
    <seq2-X>,<GET-CURRENT>:seq
    psh
    add

  [worm-advance-X]
    <seq2-X>,0,STEP:seq
]]

