# ----------------------------------------------------------------
# HSL Color Sequencer
# sequences palette colors automatically
# ----------------------------------------------------------------

%include symbols
%run-macro start

$angle 60
$stepsize 2
$time 100

[start]
    {seq-hsl},360
    wheel-sequencer
    (step <time>)

[step]
    <seq-hsl>,<GET-NEXT>,<stepsize>
    advance-sequence
    store
    <angle>
    recall
    set-palette-by-hue

