%include symbols

%run-macro glass-light-white

$brightness 33

[glass-light-white 10]
  (light-set-WHITE)

[glass-light-red 11]
  (light-set-RED)

[glass-light-tungsten 12]
  (light-set-TUNGSTEN)

[glass-light-neon 13]
  (light-set-NEON)

((light-setting WHITE white red))
((light-setting RED red red))
((light-setting TUNGSTEN tungsten sodium))
((light-setting NEON neon neon))

[[light-setting NAME FRONT-COLOR SIDE-COLOR
  [light-set-NAME]
    (light-side-NAME)
    (light-front-NAME)

  [light-side-NAME]
    SIDE-COLOR
    dim
    dim
    dim
    7
    repeat

  [light-front-NAME]
    FRONT-COLOR
    47
    repeat
]]

