%include symbols

%run-macro glass-light-white

$brightness 33

[glass-light-white 10]
  (light-set-white)

[glass-light-red 11]
  (light-set-red)

[glass-light-tungsten 12]
  (light-set-tungsten)

[glass-light-neon 13]
  (light-set-neon)

((light-setting white red))
((light-setting red red))
((light-setting tungsten sodium))
((light-setting neon neon))

[[light-setting FRONT-COLOR SIDE-COLOR
  [light-set-FRONT-COLOR]
    (light-side-FRONT-COLOR)
    (light-front-FRONT-COLOR)

  [light-side-FRONT-COLOR]
    SIDE-COLOR
    dim
    dim
    dim
    7
    repeat

  [light-front-FRONT-COLOR]
    FRONT-COLOR
    47
    repeat
]]

