
%include symbols

%include swinger
%include inchworm
#%include wanderer
%include hsl-sequencer

$rotate-time 30000

[fancy 11]
  (swinger-app)

[mellow 10]
  (inchworm-app)

[run0 9]
  (run1 0)
  (run2 0)

[run1 12]
  (swinger-app)
  (run0)
  (run2 <rotate-time>)

[run2]
  (inchworm-app)
  (run0)
  (run1 <rotate-time>)

#[run3]
#  (wanderer-app)
#  (run0)
#  (run1 <rotate-time>)

%run-macro run1

