# ----------------------------------------------------------------
# Slowly rotating color cycle
# ----------------------------------------------------------------

%include symbols
%include hsl-sequencer

%play-macro colors-app

$render-time 100
$draw-time 1000
$the-color <RED>

[colors-app 10]
  start-application
  (color-draw <draw-time>)
  (hsl-sequencer-start)
  (hsl-sequencer <draw-time>)
  (render <render-time>)

[color-draw]
  <the-color>
  add-palette-color
  fill
 
