# ----------------------------------------------------------------
# ----------------------------------------------------------------

%include symbols
%include hsl-sequencer

%play-macro colors-app

$render-time 100
$draw-time 1000
$the-color <RED>

[colors-app 10]
  application
  (render <render-time>)
  (color-draw <draw-time>)
  (hsl-sequencer-start)
  (hsl-sequencer <draw-time>)

[color-draw]
  <the-color>
  palette-color
  flood
 
