# ----------------------------------------------------------------
# HSL Color Sequencer
# sequences palette colors automatically
# ----------------------------------------------------------------

%include symbols
%play-macro start

$ANGLE 60
$STEP 2
$TIME 100

[start]
    {seq-hsl}, 360
    start-wheel-sequence

    (step <TIME>)

[step]
    {seq-hsl}, <GET-NEXT>, <STEP>
    advance-sequence
    store

    <ANGLE>
    recall

    set-palette-by-hue

