# init
10;-1:sch:-1:pau:2:cnt:11:run
11;100,13:sch:12:run
12;14:run:24:run

# display
13;flu

# seq 0-2
# init
14;0,15:sqs:1,90:sqs:2,75:sqs:15:run
15;50,16:sch:200,18:sch

# render
16;1,-4,17:snw:pos:0,0,1:pal:ffd:1:flo:rst
# advance
17;0,0,1:seq:psh:2,-1:seq:psh:mth:rcl
18;2,0,2:seq


# seq 3-5
# init
24;3,15:sqs:4,90:sqs:5,75:sqs:25:run
25;49,26:sch:199,28:sch

# render
26;4,-4,27:snw:pos:3,0,1:pal:ffd:1:flo:rst
# advance
27;3,0,1:seq:psh:5,-1:seq:psh:mth:rcl
28;5,0,2:seq


