import re

def translate(line):
    regex = "(\s|[^a-z0-9-])"
    words = re.compile(regex).split(line)

    new_words = []
    for word in words:
        if word in long_commands.keys():
            new_words.append(long_commands[word])
        else:
            new_words.append(word)

    return "".join(new_words)

    #stripped_long_command = long_command.strip()
    #if stripped_long_command in long_commands.keys():
    #    return long_commands[stripped_long_command]
    #else:
    #    return long_command

long_commands = {
 "flush" : "flu",
 "refresh-display" : "flu",
 "reset" : "rst",
 "reset-buffer" : "rst",
 "erase" : "era",
 "erase-buffer" : "era",
 "rotate" : "rot",
 "repeat" : "rep",
 "copy" : "cpy",
 "paste" : "cpy",
 "duplicate" : "cpy",
 "flood" : "flo",
 "fill" : "flo",
 "mirror" : "mir",
 "display" : "dis",			# deprecated
 "set-display" : "dis",
 "zone" : "zon",
 "set-zone" : "zon",
 "window" : "win",
 "set-window" : "win",
 "offset" : "off",
 "set-offset" : "off",
 "reverse" : "rev",
 "set-reverse" : "rev",
 "red-green-blue" : "rgb",           	# deprecated
 "rgb-color" : "rgb",			# deprecated
 "add-rgb-color" : "rgb",
 "hue-saturation-lightness" : "hsl", 	# deprecated
 "hsl-color" : "hsl",			# deprecated
 "add-hsl-color" : "hsl",
 "red" : "red",
 "orange" : "org",
 "yellow" : "yel",
 "green" : "grn",
 "blue" : "blu",
 "purple" : "pur",
 "cyan" : "cyn",
 "magenta" : "mag",
 "light-blue" : "lbl",
 "light-green" : "lgr",
 "seafoam-green" : "sea",
 "pink" : "pnk",
 "amber" : "amb",
 "olive" : "olv",
 "sky-blue" : "sky",
 "tuquoise" : "tur",
 "lavender" : "lav",
 "rose" : "ros",
 "dark-gray" : "dgr",
 "gray" : "gry",
 "white" : "wht",
 "tungsten" : "tun",
 "neon" : "neo",
 "sodium" : "sod",
 "black" : "blk",
 "random-color" : "rnd",
 "add-random-color" : "rnd",
 "dynamic-color" : "dyn",
 "add-dynamic-color" : "dyn",
 "blend" : "ble",
 "blend-colors" : "ble",
 "maximize" : "max",
 "maximize-brightness" : "max",
 "dim" : "dim",
 "darken" : "dim",
 "brighten" : "brt",
 "static" : "sta",
 "add-static" : "sta",
 "blink" : "bli",
 "set-blink" : "bli",
 "blink-1" : "bl1",
 "set-blink-1" : "bl1",
 "blink-2" : "bl2",
 "set-blink-2" : "bl2",
 "blink-3" : "bl3",
 "set-blink-3" : "bl3",
 "blink-4" : "bl4",
 "set-blink-4" : "bl4",
 "blink-5" : "bl5",
 "set-blink-5" : "bl5",
 "blink-6" : "bl6",
 "set-blink-6" : "bl6",
 "blink-a" : "bla",
 "set-blink-a" : "bla",
 "blink-b" : "blb",
 "set-blink-b" : "blb",
 "dynamic-blink" : "bld",
 "set-dynamic-blink" : "bld",
 "breathe" : "bre",
 "set-breathe" : "bre",
 "dynamic-breate" : "brd",
 "set-dynamic-breate" : "brd",
 "slow-fade" : "sfd",
 "set-slow-fade" : "sfd",
 "fast-fade" : "ffd",
 "set-fast-fade" : "ffd",
 "store" : "sto",
 "recall" : "rcl",
 "push" : "psh",
 "pause" : "pau",
 "pause-effects" : "1:pau",
 "pause-schedules" : "2:pau",
 "continue" : "cnt",
 "continue-effects" : "1:cnt",
 "continue-schedules" : "2:cnt",
 "clear" : "clr",
 "level" : "lev",            		# deprecated
 "set-brightness-level" : "lev",	# deprecated
 "set-brightness" : "lev",
 "fade" : "fad",
 "do-fade-animation" : "fad",
 "animated-rotate" : "art",
 "do-animated-rotation" : "art",
 "crossfade" : "cfa",
 "do_crossfade" : "cfa",
 "random-blink" : "blr",
 "set-random-blink" : "blr",
 "random-effect" : "efr",
 "set-random-effect" : "efr",
 "test" : "tst",
 "inquire" : "tst",
 "configure" : "cfg",
 "set-pin" : "pin",
 "schedule" : "sch",
 "set-schedule" : "sch",
 "carry-color" : "car",
 "add-carry-color" : "car",
 "set-macro" : "set",
 "run-macro" : "run",
 "delay" : "del",
 "stop" : "stp",
 "random-number" : "rng",
 "get-random-number" : "rng",
 "position" : "pos",
 "set-position" : "pos",
 "random-position" : "rps",
 "set-random-position" : "rps",
 "xy-position" : "xyp",
 "set-xy-position" : "xyp",
 "palette-color" : "pal",
 "add-palette-color" : "pal",
 "shuffle" : "shf",
 "shuffle-palette" : "shf",
 "reset-palette" : "1:shf",
 "set-black-level" : "sbl",
 "sequence" : "seq",
 "advance-sequence" : "seq",
 "wheel-sequencer" : "seq",
 "start-wheel-sequence" : "seq",
 "swing-sequencer" : "sqs",
 "start-swing-sequence" : "sqs",
 "wheel-cosine-sequencer" : "swc",
 "start-cosine-sequence" : "swc",
 "wheel-sine-sequencer" : "sws",
 "start-sine-sequence" : "sws",
 "sequence-next-window" : "snw",
 "color-sequence-hue" : "csh",
 "set-palette-by-hue" : "csh",
 "color-sequence-saturation" : "css",
 "set-palette-by-saturation" : "css",
 "color-sequence-lightness" : "csl",
 "set-palette-by-lightness" : "csl",
 "enable-fan" : "fan",
 "set-fan-enable" : "fan",
 "application" : "app",
 "start-application" : "app",
 "add" : "add",
 "+equals" : "add",
 "subtract" : "sub",
 "-equals" : "sub",
 "multiply" : "mul",
 "*equals" : "mul",
 "divide" : "div",
 "/equals" : "div",
 "modulo" : "mod",
 "%equals" : "mod",
 "difference" : "dif",
 "|equals" : "dif",
 "average" : "avg",
 "^equals" : "avg",
 "draw-mode" : "drw",      # deprecated
 "set-draw-mode" : "drw",
 "clear-schedules" : "-1:sch",
 "true" : "1",
 "false" : "0",
 "enable" : "1",
 "disable" : "0",
 "on" : "1",
 "off" : "0"
}

