10;-1:sch:1:pau:2:cnt:era:flu:11:run
11;50,12:sch:13:run
12;flu
13;25:run:35:run:15:run:20:run




15;0,90,0:seq:100,16:sch
16;0,-4,17:snw:pos:3,0,1:pal:ffd:flo:rst
17;2,-2:seq:psh:4,-2:seq:psh:mth:2:psh:3:mth:40:psh:mth




20;1,90,0:seq:100,21:sch
21;1,-4,22:snw:pos:5,0,1:pal:ffd:flo:rst
22;2,-2:seq:psh:4,-2:seq:psh:1:mth:40:psh:mth:2:psh:3:mth:40:psh:mth







25;2,24,0:swc:100,26:sch
26;2:snw:pos:0,0,1:pal:ffd:flo:rst




35;4,24,0:sws:100,36:sch
36;4:snw:pos:4,0,1:pal:ffd:flo:rst






