# rainbow wandering pixels with mirror

%include symbols

$max <NUM-LEDS>
$max-half <max>
$render-time 50
$sequence-time 20
$fade-type ffd

$wander-range 3
$wander-neg-range `-(<wander-range> / 2)`

$brightness 20

[fancy 10]
    (init)
    (setup-rendering)
    (start-components)

[init]
    app
    <brightness>:lev

[setup-rendering]
    <render-time>,<render>:sch

[render !]
    flu

[start-components]
    (start-RED)
    (start-ORANGE)
    (start-YELLOW)
    (start-GREEN)
    (start-BLUE)
    (start-PURPLE)

((wanderer RED))
((wanderer ORANGE))
((wanderer YELLOW))
((wanderer GREEN))
((wanderer BLUE))
((wanderer PURPLE))

[[wanderer X
    [start-X]
        {seq-X},<max>,0:seq
        <sequence-time>,<sequence-X>:sch

    [sequence-X]
        <seq-X>,<MACRO-SEQ>,<math-X>:seq
        pos
        <seq-X>,0,<ADD-COLOR>:pal
        <fade-type>
        rst

    [math-X]
        <wander-range>:rng:psh
        <wander-neg-range>:psh
        add
        <seq-X>,<GET-CURRENT>:seq:psh
        add
        <max-half>:psh
        mod
]]

