10;-1:sch:1:pau:2:cnt:era:flu:11:run:13:run

11;50,12:sch
12;flu

13;15:run:20:run:25:run




15;0,90,0:seq:20,16:sch
16;0,-4,17:snw:pos:0,0,1:pal:ffd:flo:rst
17;3:rng:psh:-1:psh:mth:0,-1:seq:psh:mth:90:psh:4:mth



20;1,90,0:seq:20,21:sch
21;1,-4,22:snw:pos:3,0,1:pal:ffd:flo:rst
22;3:rng:psh:-1:psh:mth:1,-1:seq:psh:mth:90:psh:4:mth




25;2,90,0:seq:20,26:sch
26;2,-4,27:snw:pos:4,0,1:pal:ffd:flo:rst
27;3:rng:psh:-1:psh:mth:2,-1:seq:psh:mth:90:psh:4:mth



